/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** health check + สถานะพอร์ทัล CSMJU2030 */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ข้อมูลผู้ใช้ปัจจุบัน */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** สถานะคำร้อง */
        get: operations["LookupsController_requestStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/urgency-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ระดับความเร่งด่วน */
        get: operations["LookupsController_urgencyLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scholarship-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ประเภททุน */
        get: operations["LookupsController_scholarshipTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issue-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ประเภทความเดือดร้อน */
        get: operations["LookupsController_issueTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** สถานภาพครอบครัว */
        get: operations["LookupsController_familyStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payout-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ช่องทางรับเงิน */
        get: operations["LookupsController_payoutMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scholarships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการประกาศทุน */
        get: operations["ScholarshipsController_list"];
        put?: never;
        /** สร้างประกาศทุน (เจ้าหน้าที่) */
        post: operations["ScholarshipsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scholarships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายละเอียดประกาศทุน */
        get: operations["ScholarshipsController_findOne"];
        put?: never;
        post?: never;
        /** ลบประกาศทุนที่ยังไม่มีใบสมัคร (ผู้ดูแลระบบ) */
        delete: operations["ScholarshipsController_remove"];
        options?: never;
        head?: never;
        /** แก้ไข / เปิด-ปิดประกาศทุน (เจ้าหน้าที่) */
        patch: operations["ScholarshipsController_update"];
        trace?: never;
    };
    "/api/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการคำร้อง (นักศึกษาเห็นเฉพาะของตัวเอง · เจ้าหน้าที่เห็นทั้งหมด) */
        get: operations["RequestsController_list"];
        put?: never;
        /** ยื่นใบสมัครทุน / คำร้องขอความช่วยเหลือฉุกเฉิน (นักศึกษา) */
        post: operations["RequestsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายละเอียดคำร้อง พร้อมไฟล์แนบและประวัติสถานะ */
        get: operations["RequestsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** เจ้าหน้าที่: เปลี่ยนสถานะ/บันทึกผลพิจารณา · เจ้าของ: แก้ไขหรือยกเลิกคำร้องที่ยังรอพิจารณา */
        patch: operations["RequestsController_update"];
        trace?: never;
    };
    "/api/v1/requests/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการไฟล์แนบของคำร้อง */
        get: operations["AttachmentsController_list"];
        put?: never;
        /** แนบไฟล์หลักฐานให้คำร้องของตัวเอง (multipart field: file) */
        post: operations["AttachmentsController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** เปิดไฟล์แนบ (เจ้าของคำร้อง หรือเจ้าหน้าที่) */
        get: operations["AttachmentsController_open"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/request-statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** สรุปภาพรวมคำร้องสำหรับหน้าเจ้าหน้าที่ */
        get: operations["StatisticsController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PortalDto: {
            /**
             * @description เว็บพอร์ทัล CSMJU2030 (Core Hub)
             * @example http://localhost:3100
             */
            url: string;
            /** @description พอร์ทัลออนไลน์อยู่หรือไม่ (ตรวจทุก 30 วินาที) */
            reachable: boolean;
        };
        HealthDto: {
            /** @enum {string} */
            status: "ok";
            /** @example csmju-scholarship */
            service: string;
            portal: components["schemas"]["PortalDto"];
        };
        PaginationMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        ErrorDetailDto: {
            /** @enum {string} */
            code: "BAD_REQUEST" | "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "TOO_MANY_REQUESTS" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE";
            message: string;
            details?: string[];
        };
        ErrorBodyDto: {
            /** @enum {boolean} */
            success: false;
            error: components["schemas"]["ErrorDetailDto"];
        };
        SessionDto: {
            /** Format: date-time */
            expiresAt: string;
        };
        PersonDto: {
            personCode: string;
            /** @example STUDENT */
            personType: string;
            fullNameTh: string;
            fullNameEn: string | null;
            /** @description ปี พ.ศ. ที่เข้าศึกษา */
            entryYear: number | null;
            /** @example ACTIVE */
            status: string;
            facultyCode: string | null;
            facultyName: string | null;
            departmentCode: string | null;
            departmentName: string | null;
            curriculumName: string | null;
            universityEmail: string | null;
        };
        LastApplicationDto: {
            contactPhone: string;
            payoutCode: string;
            payoutAccount: string;
            gpa: number | null;
            age: number | null;
            nationality: string | null;
        };
        MeDto: {
            /** @description Core Hub user id (token.sub) */
            id: string;
            email: string;
            /** @enum {string} */
            coreRole: "student" | "alumni" | "staff" | "lecturer" | "guest" | "admin";
            /** @enum {string} */
            subsystemRole: "STUDENT" | "STAFF" | "ADMIN";
            permissions: string[];
            session: components["schemas"]["SessionDto"];
            /** @description จาก Core Hub /people/me */
            person: components["schemas"]["PersonDto"] | null;
            /** @enum {string} */
            personStatus: "linked" | "unlinked" | "unavailable";
            lastApplication: components["schemas"]["LastApplicationDto"] | null;
        };
        LookupItemDto: {
            code: string;
            label: string;
            /** @enum {string} */
            tone?: "neutral" | "info" | "warning" | "success" | "danger";
            isFinal?: boolean;
            sortOrder: number;
            isActive: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        ScholarshipDto: {
            /** Format: uuid */
            id: string;
            title: string;
            typeCode: string;
            typeLabel: string;
            /** @description สตางค์ */
            amountMinSatang: number;
            /** @description สตางค์ */
            amountMaxSatang: number;
            amountNote: string;
            /** @example 5,000 บาท / ภาคเรียน */
            amountLabel: string;
            /**
             * Format: date
             * @example 2026-11-30
             */
            deadline: string;
            /** @description จำนวนวันถึงวันปิดรับ (เวลาไทย) ติดลบ = เลยแล้ว */
            daysLeft: number;
            isExpired: boolean;
            isClosingSoon: boolean;
            /** @description 0 = ไม่จำกัด */
            quota: number;
            /** @example 2.5 */
            minGpa: number;
            criteria: string;
            description: string;
            isActive: boolean;
            applicationCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateScholarshipDto: {
            /** @example ทุนสนับสนุนการศึกษา สาขาวิทยาการคอมพิวเตอร์ ภาคเรียนที่ 2/2569 */
            title: string;
            /** @example DEPARTMENT */
            typeCode: string;
            /**
             * @description วงเงินขั้นต่ำ (สตางค์)
             * @example 500000
             */
            amountMinSatang: number;
            /**
             * @description วงเงินสูงสุด (สตางค์)
             * @example 500000
             */
            amountMaxSatang: number;
            /** @example / ภาคเรียน */
            amountNote?: string;
            /**
             * @description วันปิดรับสมัคร YYYY-MM-DD
             * @example 2026-11-30
             */
            deadline: string;
            /**
             * @description จำนวนทุน (0 = ไม่จำกัด)
             * @example 20
             */
            quota?: number;
            /**
             * @description เกรดเฉลี่ยขั้นต่ำ 0.00–4.00
             * @example 2.5
             */
            minGpa?: number;
            criteria: string;
            description: string;
            /** @default true */
            isActive: boolean;
        };
        UpdateScholarshipDto: {
            /** @example ทุนสนับสนุนการศึกษา สาขาวิทยาการคอมพิวเตอร์ ภาคเรียนที่ 2/2569 */
            title?: string;
            /** @example DEPARTMENT */
            typeCode?: string;
            /**
             * @description วงเงินขั้นต่ำ (สตางค์)
             * @example 500000
             */
            amountMinSatang?: number;
            /**
             * @description วงเงินสูงสุด (สตางค์)
             * @example 500000
             */
            amountMaxSatang?: number;
            /** @example / ภาคเรียน */
            amountNote?: string;
            /**
             * @description วันปิดรับสมัคร YYYY-MM-DD
             * @example 2026-11-30
             */
            deadline?: string;
            /**
             * @description จำนวนทุน (0 = ไม่จำกัด)
             * @example 20
             */
            quota?: number;
            /**
             * @description เกรดเฉลี่ยขั้นต่ำ 0.00–4.00
             * @example 2.5
             */
            minGpa?: number;
            criteria?: string;
            description?: string;
            /** @default true */
            isActive: boolean;
        };
        DeletedDto: {
            /** Format: uuid */
            id: string;
            /** @enum {boolean} */
            deleted: true;
        };
        ApplicantDto: {
            /** @description รหัสนักศึกษาจาก Core Hub /people/me ตอนยื่น */
            personCode: string | null;
            contactPhone: string;
            gpa: number | null;
            age: number | null;
            nationality: string | null;
            /** @description เฉพาะเจ้าหน้าที่ */
            nationalId?: string | null;
        };
        RequestSummaryDto: {
            /** Format: uuid */
            id: string;
            /** @example MJU-SCH-2026-0001 */
            trackingNo: string;
            /** @enum {string} */
            kind: "SCHOLARSHIP" | "WELFARE";
            coreUserId: string;
            applicant: components["schemas"]["ApplicantDto"];
            scholarshipId: string | null;
            scholarshipTitle: string | null;
            issueCode: string | null;
            issueLabel: string | null;
            urgencyCode: string | null;
            urgencyLabel: string | null;
            urgencyTone: string | null;
            familyIncomeSatang: number | null;
            familyStatusCode: string | null;
            familyStatusLabel: string | null;
            familyExpenses: string | null;
            amountRequestedSatang: number;
            amountApprovedSatang: number | null;
            payoutCode: string;
            payoutLabel: string;
            payoutAccount: string;
            reason: string;
            statusCode: string;
            statusLabel: string;
            statusTone: string;
            isFinal: boolean;
            staffNote: string;
            attachmentCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AttachmentDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            requestId?: string;
            originalName: string;
            mimeType: string;
            sizeBytes: number;
            /** Format: date-time */
            createdAt: string;
        };
        StatusHistoryDto: {
            /** Format: uuid */
            id: string;
            fromStatusCode: string | null;
            toStatusCode: string;
            toStatusLabel: string;
            toStatusTone: string;
            note: string;
            /** @enum {string} */
            changedByRole: "STUDENT" | "STAFF" | "ADMIN";
            /** Format: date-time */
            createdAt: string;
        };
        RequestDetailDto: {
            /** Format: uuid */
            id: string;
            /** @example MJU-SCH-2026-0001 */
            trackingNo: string;
            /** @enum {string} */
            kind: "SCHOLARSHIP" | "WELFARE";
            coreUserId: string;
            applicant: components["schemas"]["ApplicantDto"];
            scholarshipId: string | null;
            scholarshipTitle: string | null;
            issueCode: string | null;
            issueLabel: string | null;
            urgencyCode: string | null;
            urgencyLabel: string | null;
            urgencyTone: string | null;
            familyIncomeSatang: number | null;
            familyStatusCode: string | null;
            familyStatusLabel: string | null;
            familyExpenses: string | null;
            amountRequestedSatang: number;
            amountApprovedSatang: number | null;
            payoutCode: string;
            payoutLabel: string;
            payoutAccount: string;
            reason: string;
            statusCode: string;
            statusLabel: string;
            statusTone: string;
            isFinal: boolean;
            staffNote: string;
            attachmentCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            attachments: components["schemas"]["AttachmentDto"][];
            history: components["schemas"]["StatusHistoryDto"][];
            /** @description ชื่อผู้ยื่นจาก Core Hub — เฉพาะเจ้าหน้าที่ · หาไม่ได้ = null */
            person: components["schemas"]["PersonDto"] | null;
        };
        CreateRequestDto: {
            /** @enum {string} */
            kind: "SCHOLARSHIP" | "WELFARE";
            /**
             * @description เบอร์ติดต่อกลับสำหรับคำร้องนี้ 10 หลัก ไม่มีขีด
             * @example 0812345678
             */
            contactPhone: string;
            /** @example PROMPTPAY */
            payoutCode: string;
            /** @example 0812345678 */
            payoutAccount: string;
            /**
             * @description จำนวนเงินที่ขอรับ (สตางค์)
             * @example 500000
             */
            amountRequestedSatang: number;
            reason: string;
            /** Format: uuid */
            scholarshipId?: string;
            /** @description เลขบัตรประชาชน 13 หลัก */
            nationalId?: string;
            /** @example 3.25 */
            gpa?: number;
            /** @example 20 */
            age?: number;
            /** @example ไทย */
            nationality?: string;
            /** @description รายได้ครอบครัวต่อปี (สตางค์) */
            familyIncomeSatang?: number;
            /** @example TOGETHER */
            familyStatusCode?: string;
            familyExpenses?: string;
            /** @example MEDICAL */
            issueCode?: string;
            /** @example URGENT */
            urgencyCode?: string;
            /** @description ต้องเป็น true — รับรองว่าข้อมูลเป็นความจริง */
            acceptTerms?: boolean;
        };
        UpdateRequestDto: {
            /** @example UNDER_REVIEW */
            statusCode?: string;
            staffNote?: string;
            /** @description วงเงินที่อนุมัติ (สตางค์) */
            amountApprovedSatang?: number;
            /** @description จำนวนเงินที่ขอรับ (สตางค์) */
            amountRequestedSatang?: number;
            reason?: string;
            /** @example PROMPTPAY */
            payoutCode?: string;
            payoutAccount?: string;
            familyExpenses?: string;
            /** @example URGENT */
            urgencyCode?: string;
            /** @description เหตุผลที่ยกเลิก/แก้ไข (บันทึกลงประวัติ) */
            changeNote?: string;
        };
        StatusCountDto: {
            code: string;
            label: string;
            tone: string;
            total: number;
        };
        MonthlyCountDto: {
            /** @example 2026-09 */
            month: string;
            /** @example ก.ย. 69 */
            label: string;
            scholarship: number;
            welfare: number;
        };
        CodeCountDto: {
            code: string;
            label: string;
            tone?: string;
            total: number;
        };
        TopScholarshipDto: {
            /** Format: uuid */
            id: string;
            title: string;
            quota: number;
            applicationCount: number;
            approvedCount: number;
        };
        RequestStatisticsDto: {
            byStatus: components["schemas"]["StatusCountDto"][];
            /** @description คำร้องที่ยังไม่สิ้นสุด */
            awaitingActionCount: number;
            /** @description รออาจารย์ที่ปรึกษาเกิน 7 วัน */
            overdueCount: number;
            /** @description อนุมัติ / (อนุมัติ + ไม่ผ่าน) */
            approvalRatePercent: number | null;
            monthly: components["schemas"]["MonthlyCountDto"][];
            byIssueType: components["schemas"]["CodeCountDto"][];
            openByUrgency: components["schemas"]["CodeCountDto"][];
            topScholarships: components["schemas"]["TopScholarshipDto"][];
            scholarshipRequestCount: number;
            welfareRequestCount: number;
            totalRequestedSatang: number;
            totalApprovedSatang: number;
            activeScholarshipCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["HealthDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MeDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    LookupsController_requestStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LookupItemDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    LookupsController_urgencyLevels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LookupItemDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    LookupsController_scholarshipTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LookupItemDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    LookupsController_issueTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LookupItemDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    LookupsController_familyStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LookupItemDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    LookupsController_payoutMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["LookupItemDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    ScholarshipsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description รวมประกาศที่ปิดแล้ว (เฉพาะเจ้าหน้าที่) */
                includeInactive?: boolean;
                typeCode?: string;
                /** @description ค้นจากชื่อทุน/เกณฑ์ */
                q?: string;
                /** @description เฉพาะทุนที่ปิดรับภายใน N วัน (ยังไม่หมดเขต) */
                closingWithinDays?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ScholarshipDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    ScholarshipsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScholarshipDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ScholarshipDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    ScholarshipsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ScholarshipDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    ScholarshipsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    ScholarshipsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScholarshipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ScholarshipDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    RequestsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                kind?: "SCHOLARSHIP" | "WELFARE";
                statusCode?: string;
                /** @description รหัสติดตามคำร้อง เช่น MJU-SCH-2026-0001 */
                trackingNo?: string;
                /** @description ค้นจากชื่อ รหัสนักศึกษา รหัสติดตาม หรือชื่อทุน */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RequestSummaryDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    RequestsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RequestDetailDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    RequestsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RequestDetailDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    RequestsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RequestDetailDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    AttachmentsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AttachmentDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    AttachmentsController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AttachmentDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
    AttachmentsController_open: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ไฟล์ต้นฉบับ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
        };
    };
    StatisticsController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RequestStatisticsDto"];
                    };
                };
            };
            /** @description error envelope */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBodyDto"];
                };
            };
        };
    };
}
